##################################################################################
########################          SAMPLES          ###############################
##################################################################################
samples: "sample1 sample2 sample3
sample4 sample5 sample6"

lane: ""

reads: "1 2"

fq: ".fastq.gz"

##################################################################################
########################        STEP NAMES         ###############################
##################################################################################
step_qC: qC/ # quality control
step_map: map/ # map to reference
step_counts: counts/ # counts

##################################################################################
###########################        INFO        ###################################
##################################################################################
# adapters
adapters: "TruSeq3-PE-2.fa"

# threads
threads: 50

## Directories
# Base data dir
base_dir: /home/user/

# Change to location of all raw .sam files
raw_data_dir: /home/user/rnaseq/specie/

# Path to trimmed reads output
trimmed_dir: /home/user/rnaseq/specie/trimmed/

# Path to reference genome
ref_genome: /home/genome/Mus_musculus.GRCm39.dna.toplevel.fa

# Path to gtf file
gtf_file: /home/genome/Mus_musculus.GRCm39.105.gtf
gtf_gff: "--gtf"
#gtf_gff: "--gff3"


# Rsem prepare ref dir
rsemprepref: /home/genome/mouse/rsemRef/

# Reference prefix
prefix_ref: "mouse_ref"
