## Samples
samples: "sample1 sample2 sample3
sample4 sample5 sample6"

lane: ""

fq: ".fastq.gz"

## Step names
step_qC: qC/ # quality control
step_map: map/ # map to reference
step_counts: counts/ # counts

## Info
# adapters
adapters: "TruSeq3-SE-2.fa"
# threads
threads: 50

## Directories
# Base data dir
base_dir: /home/user/rnaseq/

# Change to location of all raw .sam files
raw_data_dir: /home/user/rnaseq/specie/

# Path to trimmed reads output
trimmed_dir: /home/user/rnaseq/specie/trimmed/

# Path to reference genome
ref_genome: /home/user/rnaseq/specie/ref_from_ensembl.fa

# Path to gtf file
gtf_file: /home/user/rnaseq/specie/annotation_from_ensembl.gff
gtf_gff: "--gff3"
#gtf_gff: "--gtf"

# Rsem prepare ref dir
rsemprepref: /home/user/rnaseq/specie/rsemRef/

# Reference prefix
prefix_ref: "specie_ref"
