##################################################################################
########################          SAMPLES          ###############################
##################################################################################
samples: "Diacama_sp_gamergate_gaster_DRX022365 Diacama_sp_gamergate_gaster_DRX022370 Diacama_sp_gamergate_gaster_DRX022375
Diacama_sp_worker_gaster_DRX022366 Diacama_sp_worker_gaster_DRX022371 Diacama_sp_worker_gaster_DRX022376"

lane: ""

fq: ".fastq.gz"

reads: "_1 _2"
##################################################################################
########################        STEP NAMES         ###############################
##################################################################################
step_qC: qC/ # quality control
step_assembly: assembly_trinity/ # assembly
step_map: map/ # align to assembly 
step_counts: counts/ # counts
step_transdecoder: transdecoder/
step_cdhit: cdHit/
step_annotation: annotation/


##################################################################################
###########################        INFO        ###################################
##################################################################################
# adapters
adapters: "TruSeq3-PE-2.fa"

# threads
threads: 10

## Directories
# Base data dir
base_dir: /home/buckcenter.org/nmurad/

# Change to location of all raw .sam files
raw_data_dir: /home/buckcenter.org/nmurad/antsrnaseq/Diacammasp/

# Path to trimmed reads output
trimmed_dir: /home/buckcenter.org/nmurad/antsrnaseq/Diacammasp/trimmed/

# Path to assembly output
assembly_dir: /home/buckcenter.org/nmurad/antsrnaseq/Diacammasp/assembly_trinity/

# Path to bowtie index
btIndex_dir: /home/buckcenter.org/nmurad/antsrnaseq/Tnylanderi/btIndex/