##################################################################################
########################          SAMPLES          ###############################
##################################################################################
#[Sample Name]_S1_L00[Lane Number]_[Read Type]_001.fastq.gz
#{sample}_S1{lane}{read}_001{fq}

samples: "SRR12330954 SRR12330955 SRR12330956 SRR12330957 SRR12330958
SRR12330959 SRR12330960 SRR12330961 SRR12330962 SRR12330963 SRR12330964 SRR12330965"

lane: "_L001"

reads: "_1 _2"
readssc: "_R1 _R2"

fq: ".fastq.gz"

## Step names
step_qReports: qReports # quality reports

# Threads
threads: "20"

##################################################################################
########################        DIRECTORIES        ###############################
##################################################################################

# Base data dir
base_dir: /home/user/humanOocyteAging/

# Change to location of all raw .sam files
raw_data_dir: /home/user/humanOocyteAging/


##################################################################################
########################     CELLRANGER PARAMS     ###############################
##################################################################################
# Cellranger Ref Index dir
crindexdir: /home/user/cellranger_ref/

step_cellrangerMap: cellranger_Counts/ # map to reference

#cellranger_refsite: https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-mm10-2020-A.tar.gz # mouse
cellranger_refsite: https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#GRCh38_2020A # human

#refname: refdata-gex-mm10-2020-A # mouse
refname: refdata-gex-GRCh38-2020-A # human



