##################################################################################
########################          SAMPLES          ###############################
##################################################################################

samples: "sample1 sample2 sample3
sample4 sample5 sample6"

lane: "L001"

reads: "_1 _2"

fastq: ".fastq.gz"

## Step names
step_qReports: qReports # quality reports

# Threads
threads: "50"

##################################################################################
########################     CELLRANGER PARAMS     ###############################
##################################################################################
# Cellranger Ref Index dir
crindexdir: /home/user/cellranger_ref/

# Data dir
raw_data_dir: /home/user/rnaseq/specie/

step_cellrangerMap: cellRangerMap/ # map to reference

# MOUSE
#cellranger_refsite: https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-mm10-2020-A.tar.gz

# HUMAN
cellranger_refsite: https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz

# MOUSE
#refname: refdata-gex-mm10-2020-A

# HUMAN
refname: refdata-gex-GRCh38-2020-A
