## Samples
samples: "M.pharaonis_focal_nurse_gaster_SAMD00027125 M.pharaonis_focal_nurse_gaster_SAMD00027131 M.pharaonis_forager_gaster_SAMD00027111
M.pharaonis_forager_gaster_SAMD00027118 M.pharaonis_nurse_gaster_SAMD00027137 M.pharaonis_nurse_gaster_SAMD00027139 M.pharaonis_queen_gaster_SAMD00026921
M.pharaonis_queen_gaster_SAMD00027141"

lane: ""

fq: "fastq.gz"

## Step names
step_qC: qC # quality control
step_map: map # map to reference
step_counts: counts # counts

## Info
# adapters
adapters: /home/microgravity/adapters.fa

# threads
threads: 50

## Directories
# Base data dir
base_dir: /home/

# Change to location of all raw .sam files
raw_data_dir: /home/antsRNAseq/M. pharaonis/

# Path to trimmed reads output
trimmed_dir: /home/antsRNAseq/M. pharaonis/trimmed/

# Path to reference genome
ref_genome: /home/antsRNAseq/M. pharaonis/GCF_013373865.1_ASM1337386v2_genomic.fna

# Path to gtf file
gtf_file: /home/antsRNAseq/M. pharaonis/GCF_013373865.1_ASM1337386v2_genomic.gff

# Genome index dir
genomeindexdir: /home/antsRNAseq/M. pharaonis/starIndex/

# Rsem prepare ref dir
rsemprepref: /home/antsRNAseq/M. pharaonis/rsemRef/

# Reference prefix
prefix_ref: "mpharaonis_ref"
