##################################################################################
########################          SAMPLES          ###############################
##################################################################################
samples: "sample1 sample2 sample3
sample4 sample5 sample6"

lane: ""

fq: ".fastq.gz"

reads: ""

contrasts: "A_vs_B"
##################################################################################
########################        STEP NAMES         ###############################
##################################################################################
step_qC: qC/ # quality control
step_assembly: assembly_trinity/ # assembly
step_map: map/ # align to assembly 
step_counts: counts/ # counts
step_transdecoder: transdecoder/
step_cdhit: cdHit/
step_annotation: annotation/


##################################################################################
###########################        INFO        ###################################
##################################################################################
# adapters
adapters: "TruSeq2-SE.fa"

# threads
threads: 20

## Directories
# Base data dir
base_dir: /home/user/rnaseq/

# Change to location of all raw .sam files
raw_data_dir: /home/user/rnaseq/specie/

# Path to trimmed reads output
trimmed_dir: /home/user/rnaseq/specie/trimmed/

# Path to assembly output
assembly_dir: /home/user/rnaseq/specie/assembly_trinity/trinity/

# Assembly file name
assembly_name: Trinity-GG.fasta
#trinity.Trinity.fasta
# Path to bowtie index
#btIndex_dir: /home/buckcenter.org/nmurad/antsrnaseq/Hsaltator/btIndex/

# Path to reference genome
ref_genome: /home/user/rnaseq/specie/GCF_reference_from_ensembl.fa

# Path to gtf file
gtf_file: /home/user/rnaseq/specie/annotation_from_ensembl.gff
gtf_gff: --gff3

# Rsem prepare ref dir
rsemprepref: /home/user/rnaseq/specie/genomeIndex/

# Reference prefix
prefix_ref: "specie_ref"