##################################################################################
########################          SAMPLES          ###############################
##################################################################################
samples: "SAMPLE1 SAMPLE2 SAMPLE3 SAMPLE4
SAMPLE5 SAMPLE6 SAMPLE7 SAMPLE8"

lane: ""

fq: ".fastq.gz"

reads: ""
##################################################################################
########################        STEP NAMES         ###############################
##################################################################################
step_qC: qC/ # quality control
step_assembly: assembly_trinity/ # assembly
step_map: map/ # align to assembly 
step_counts: counts/ # counts
step_transdecoder: transdecoder/
step_cdhit: cdHit/
step_annotation: annotation/


##################################################################################
###########################        INFO        ###################################
##################################################################################
# adapters
adapters: "TruSeq3-SE-2.fa"

# threads
threads: 50

## Directories
# Base data dir
base_dir: /home/user/

# Change to location of all raw .sam files
raw_data_dir: /home/user/data/specie/

# Path to trimmed reads output
trimmed_dir: /home/user/data/specie/trimmed/

# Path to assembly output
assembly_dir: /home/user/data/specie/assembly_trinity/

# Path to bowtie index
btIndex_dir: /home/user/data/specie/btIndex/

