##################################################################################
########################          SAMPLES          ###############################
##################################################################################
samples: "Tnyladeri_queen_abdomen_SAMN16591861	Tnyladeri_queen_abdomen_SAMN16591864	 Tnyladeri_worker_abdomen_SAMN16591867
Tnyladeri_queen_abdomen_SAMN16591862	Tnyladeri_worker_abdomen_SAMN16591865  Tnyladeri_worker_abdomen_SAMN16591868
Tnyladeri_queen_abdomen_SAMN16591863	Tnyladeri_worker_abdomen_SAMN16591866"

lane: ""

fq: ".fastq.gz"

reads: ""
##################################################################################
########################        STEP NAMES         ###############################
##################################################################################
step_qC: qC/ # quality control
step_assembly: assembly_trinity/ # assembly
step_map: map/ # align to assembly 
step_counts: counts/ # counts
step_transdecoder: transdecoder/
step_cdhit: cdHit/
step_annotation: annotation/


##################################################################################
###########################        INFO        ###################################
##################################################################################
# adapters
adapters: "TruSeq3-SE-2.fa"

# threads
threads: 50

## Directories
# Base data dir
base_dir: /home/buckcenter.org/nmurad/

# Change to location of all raw .sam files
raw_data_dir: /home/buckcenter.org/nmurad/antsrnaseq/Tnylanderi/

# Path to trimmed reads output
trimmed_dir: /home/buckcenter.org/nmurad/antsrnaseq/Tnylanderi/trimmed/

# Path to assembly output
assembly_dir: /home/buckcenter.org/nmurad/antsrnaseq/Tnylanderi/assembly_trinity/

# Path to bowtie index
btIndex_dir: /home/buckcenter.org/nmurad/antsrnaseq/Tnylanderi/btIndex/

# Path to reference genome
#ref_genome: /home/genome/Mus_musculus.GRCm39.dna.toplevel.fa

# Path to gtf file
#gtf_file: /home/genome/Mus_musculus.GRCm39.105.gtf

# Genome index dir
#genomeindexdir: /home/genome/Human/starIndex/

# Rsem prepare ref dir
#rsemprepref: /home/genome/Human/rsemRef/

# Reference prefix
#prefix_ref: "human_ref"

