## Samples
samples: "SAMPLE1 SAMPLE2 SAMPLE3 SAMPLE4
SAMPLE5 SAMPLE6 SAMPLE7 SAMPLE8"

lane: ""

fq: "fastq.gz"

## Step names
step_qC: qC # quality control
step_map: map # map to reference
step_counts: counts # counts

## Info
# adapters
adapters: /home/user/adapters.fa

# threads
threads: 50

## Directories
# Base data dir
base_dir: /home/user/

# Change to location of all raw .sam files
raw_data_dir: /home/user/specie/

# Path to trimmed reads output
trimmed_dir: /home/user/specie/trimmed/

# Path to reference genome
ref_genome: /home/user/specie/GCF_013373865.1_ASM1337386v2_genomic.fna

# Path to gtf file
gtf_file: /home/user/specie/GCF_013373865.1_ASM1337386v2_genomic.gff

# Genome index dir
genomeindexdir: /home/user/specie/starIndex/

# Rsem prepare ref dir
rsemprepref: /home/user/specie/rsemRef/

# Reference prefix
prefix_ref: "specie_ref"
