##################################################################################
########################          SAMPLES          ###############################
##################################################################################
samples: "sample1 sample2 sample3"

lane: "_L005_R1_001"

reads: ""

fq: ".fastq.gz"

##################################################################################
########################        STEP NAMES         ###############################
##################################################################################
step_qC: qC/ # quality control
step_map: map/ # map to reference
step_counts: counts/ # counts

##################################################################################
###########################        INFO        ###################################
##################################################################################
# adapters
adapters: "TruSeq3-SE.fa"
# threads
threads: 10

## Directories
# Base data dir
base_dir: /home/user/data/

# Change to location of all raw .sam files
raw_data_dir: /home/user/data/

# Path to trimmed reads output
trimmed_dir: /home/user/data/trimmed/

# Path to reference genome
ref_genome: /home/user/genome/Mus_musculus.GRCm39.dna.toplevel.fa

# Path to gtf file
gtf_file: /home/user/genome/Mus_musculus.GRCm39.110.gtf
gtf_gff: "--gtf"
#gtf_gff: "--gff3"

# Rsem prepare ref dir
rsemprepref: /home/user/genome/Mouse/rsemRef/

# Reference prefix
prefix_ref: "mouse_ref"
